image: $CI_REGISTRY/devel/scirius/iceweasel:latest

npm:
  image: node:8.9.4
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
    - rules/static/dist
    - rules/static/bundles
    - rules/static/webpack-stats.prod.json
  script:
  - npm install
  - npm install -g webpack@3.11
  - webpack
  - cd hunt
  - npm install
  - npm run build
  - node node_modules/eslint/bin/eslint.js -c .eslintrc .

test-static:
  stage: test
  script:
  - /home/admin/venv/bin/pylint --load-plugins pylint_django -E -d unexpected-keyword-arg,no-member,access-member-before-definition,no-name-in-module,import-error */*.py
  - for f in $(find .  -type f -name "*.py" ! -name "__init__.py" ! -name "manage.py" ! -name "setup.py" ! -name "yaml.py" ! -name "lineinfile.py" -not -path "./doc/*" -not -path "./rules/south_migrations/*" -not -path "./suricata/south_migrations/*" -not -path "./accounts/south_migrations/*" -not -path "./node_modules/*" -not -path "./tests/*" -not -path "./hunt/*"); do if ! grep -q 'from __future__ import unicode_literals' $f ; then echo "$f does not contain unicode_literals import"; exit 1;  fi; done
  - PYTHONIOENCODING="UTF-8" ./tests/check_non_ascii_chars.py

eslint_check:
  image: node:8.9.4
  stage: custom
  when: manual
  script:
  - cd hunt
  - npm install
  - cd ..
  - python tests/eslint_check.py $(find hunt -name \*.js |grep -v /node_modules/)
